### ISSUE TITLE
Make numerical cutoffs for things like read depth/quality filter clearer

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#1]
It's not immediately clear how the filter is going to work the way it's currently implemented. It's just "Other" and an empty box. One has to make the assumption that it will be a >= <value> by looking at the others.

![0cc2c14e-2c2e-11e3-9a77-5c858db0dae0](https://f.cloud.github.com/assets/21576/1374713/956e2642-3a74-11e3-94d6-7ed3d4360c28.png)

suggest re-phrasing the dropdown so it has the following values for read depth (and the equivalent ones for quality.
    All Depths
    >= 10 (Research)
     >= 30 (Clinical)
     >= Custom Value...

A similar approach needs to be done on the following screens as well
- [ ] Common Variants (should read <= 1% (very rare), <= 5% (rare), <= Custom Value...
- [ ] Cohort Allele Frequency (should actually have a <= leading into the text field

**Comment by naegelyd** [comment]
These have been "fixed" by moving to 2.2 which provides the classic range input for these concepts. Stats problem aside, these are all now using the range input so it should now be clear how to use these inputs.

![screen shot 2014-01-07 at 11 09 42 am](https://f.cloud.github.com/assets/3911912/1860619/2fd39a18-77b6-11e3-8fa1-15d6028bd4b6.png)
