### ISSUE TITLE
query page is sometimes blank owing to javascript errors

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#106]
Sometimes when I go to the query page, it is mostly blank. In the javascript console, I see this:

Failed to load resource: the server responded with a status of 404 (NOT FOUND) https://rescows02.research.chop.edu/varify/static/cilantro/js/templates/count.html
Uncaught Error: /varify/static/cilantro/js/templates/count.html HTTP status: 404 require.js:1
Failed to load resource: the server responded with a status of 404 (NOT FOUND) https://rescows02.research.chop.edu/varify/static/cilantro/js/cilantro/utils/numbers.js
Uncaught Error: Script error for: cilantro/utils/numbers
http://requirejs.org/docs/errors.html#scripterror require.js:1
Failed to load resource: the server responded with a status of 404 (NOT FOUND) https://rescows02.research.chop.edu/varify/static/cilantro/js/cilantro/ui/numbers.js
Uncaught Error: Script error for: cilantro/ui/numbers
http://requirejs.org/docs/errors.html#scripterror require.js:1
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.

upon refresh, it seems to correct itself, but it does happen on and off in dev quite a lot.

**Comment by naegelyd** [comment]
I still cannot recreate this. Have you encountered the problem with the latest release?

**Comment by mitalia** [comment]
No I'm not seeing it. Only thing I can think of is that data is slower over VPN and there may have been some things not loading in time for require.js. I can re-test at some point, but let's close for now.
