### ISSUE TITLE
Only SIFT calls displayed in variant details?

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#110]
I ran a query for things that had both sift and polyphen as highly damaging. I get a lot of results, and when I click on individual ones, I see SIFT listed in the variant details view, but never polyphen. This appears to have always been the case so I'm not tying this to an immediate release.

**Comment by naegelyd** [comment]
@mitalia Can you attach a screenshot of your filters here?

**Comment by mitalia** [comment]
![image](https://f.cloud.github.com/assets/21576/2211222/0d69cf7e-99a3-11e3-864a-c5b9360630bb.png)

If you open a variant, you'll see there's nothing in "prediction scores". Again, this is not a priority for this release and I can confirm similar behavior in production.
