### ISSUE TITLE
Genomic position concept

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#113]
I thought this would get fixed automatically by the cilantro update, but it looks like it didn't.  A genomic position is uniquely identified by both the chromosome and the position. Our Genomic coordinate form is not displaying the chromosome. 

![image](https://f.cloud.github.com/assets/21576/2210659/2d02b7d0-999c-11e3-8a89-d68e8f9f9f4e.png)

It does not make sense for a user to choose genomic positions wihtout first choosing a chromosome. However, it _does_ make sense to choose multiple chromosomes if one is not providing a position. For example: "show me all the variants on chromosomes 1, 2, 3" is valid. 

For reference, here's the old implementation:
![image](https://f.cloud.github.com/assets/21576/2210690/a91189dc-999c-11e3-9c83-c7d5cdd0ef39.png)

**Comment by naegelyd** [comment]
The `dist` endpoint takes forever to return. Trying to track down the reason now. That delay is the reason why there are no chromosomes displayed.

**Comment by naegelyd** [comment]
It appears that [this line](https://github.com/cbmi/serrano/blob/2.2/serrano/resources/field/dist.py#L97) is causing the issue but more generally it seems that whenever `stats` gets evaluated everything slows to a crawl.

**Comment by naegelyd** [comment]
I considered making this a `MultiSelectionList` control but then I ran into this bug: https://github.com/cbmi/cilantro/issues/423.

**Comment by mitalia** [comment]
Not knowing exactly how this works under the hood, it seems wasteful for the chromosome control to call the dist endpoint when the number of chromosomes is fixed and unchanging.

**Comment by bruth** [comment]
cbmi/cilantro#423 was fixed so the multi-select control can be used which does not call the distribution endpoint.

**Comment by mitalia** [comment]
This is the last remaining blocker bug for going to production, so I was just trying to tie up loose ends. Hopefully we can get this integrated and deployed into dev soon.
