### ISSUE TITLE
Gene Set is showing numbers and not names

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#115]
The gene set display is showing numbers instead of names:
![image](https://f.cloud.github.com/assets/21576/2210776/8a6364be-999d-11e3-953f-6139d4547f5e.png)

It should behave like the gene selection control or any other "ID-style" control

**Comment by naegelyd** [comment]
This can be fixed internally but there will still be a minor display issue until this is fixed: https://github.com/cbmi/cilantro/issues/428.

**Comment by naegelyd** [comment]
Marking as closed. This is as fixed as it can be from a Varify perspective. The Cilantro issue noted above, once resolved, will clean up the mismatch issue between item text and text area text.
