### ISSUE TITLE
Checkboxes and radio buttons broken site-wide

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#120]
I am unable to select checkboxes on our dev server as to the export format I want. This prevents export from working.

**Comment by naegelyd** [comment]
I updated the original title as this appears to be a problem with the radio buttons and checkboxes across the site as a whole. Looking in to the issue now.

**Comment by naegelyd** [comment]
Closed in favor of https://github.com/cbmi/cilantro/issues/436
