### ISSUE TITLE
Add support for Django 1.5

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#13]

**Comment by naegelyd** [comment]
Currently, I have no reason to believe that the code base is not Django 1.5 compliant other than the failing test: `tests.cases.sample_load_process.tests.SnpeffReloadTest`. The test passes fine in `1.4.10` but fails in `1.5.5`. After looking at this a bit, I am assuming there is an issue with the changes made to `TransactionTestCase` in Django 1.5 but I can't be sure. Quickly testing the history of `django/test/testcase.py` it was found that https://github.com/django/django/commit/b39b0aedbfbddf8fab0c43b92dc237caa8da375f runs fine while https://github.com/django/django/commit/b9f9bc9a170430901fae188c375076f9b2cac784 causes the tests to fail. I am not saying there is a bug in Django, I am just listing those to show where the change occurred that causes our code to fail. 

My current thinking is that there is a problem mixing transactions occurring from the sample queue command and the manually executed cursor commands run [in the reload-snpeff handler](https://github.com/cbmi/varify/blob/master/varify/variants/management/subcommands/reload_snpeff.py#L47-L55) but it's nothing more than a hunch.

The `issue-13` branch contains a couple of minor commits already and work should continue there.

**Comment by hassanNS** [comment]
The issue, as we have identified with the failing assessment tests is that Django cannot flush the db when transitioning from a `TransactionTestCase` test to a `TestCase` test. This issue is in Django `1.4.10`

**Comment by naegelyd** [comment]
This is no longer an issue after the models and loader portions of varify were split out into https://github.com/cbmi/varify-data-warehouse.

**Comment by hassanNS** [comment]
@naegelyd does this mean that the tests are passing?
