### ISSUE TITLE
Add additional information to distinguish samples

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#140]
In thinking about long-term use of Varify, there is some additional information we need to capture regarding the platform used to generate the data:

Type of data (Whole Exome, Whole Genome, Array)
Human genome version (hg18, hg19, hg20)
Target depth (for exome and genome only) (e.g. 100x, 50x, etc..)
Platform (e.g. Illumina HiSeq, Illumina Omni, etc...) 
Capture technology (e.g. Niblegen Vx, SureSelect, etc...)

This likely means a data model update and a change to the manifest file.

**Comment by naegelyd** [comment]
Closing in favor of https://github.com/cbmi/varify-data-warehouse/issues/8
