### ISSUE TITLE
Removing load off the database during VCF processing

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/varify#146]
@naegelyd and I discussed refactoring the load pipeline to not use the database during processing of VCF files. The high-level approach is as follows:
1. Populate a cache of required data for processing from the database
   - Variants are keyed by the chromosome, start and end position or by the [MD5](https://github.com/cbmi/varify/blob/master/varify/variants/utils.py#L7-L22) which is already stored in the table. This depends on `Variant`, `Chromosome` and `VariantType`.
     - _As a side note, the MD5 is only used for pipeline processing, so it could be dropped from the table altogether if they are generated dynamically during this phase. This would reduce the size of the `variant` table by a third._
   - Variant effects which depends on `Variant`, `Chromosome`, `Effect`, `FunctionalClass`, `Gene`, and `Transcript`
     - The current behavior is to only assess variant effects if the variant is new, but does not handle merges/updates to existing effects. This could be a time add support for this and log all the occurrences that effects have changed over time as new snpEff versions are released.
   - Samples are keyed by project, batch, name, version
   - Sample results are insert only, so there is no need to cache them
2. Store max surrogate key values which act as the starting point for incrementing new identifiers.
   - This enables the loader to handle incrementing it's own keys to ensure references are properly set up outside of the database
   - Memcached should be used ensure atomicity during reads and writes of these surrogate keys during parallel processing.
3. Writing out data for load
   - Generate flat TSV to be loaded into the database using Postgres' COPY command (fastest)
     - Generic format to easily make data assertions using all kinds of tools, visual inspection, etc.
   - Write to temporary empty postgres database that is then sync it with the targets
     - Full power of SQL to make assertions, compute stats to be applied as the diff to existing ones

**Comment by bruth** [comment]
Also, for a reference, all of the necessary data for processing is about ~2 GB as it stands in production. That is with 17 million variants, 51K genes, and 215K transcripts. All this could easily fit into an in-memory SQLite database, redis, memcache, etc.

**Comment by mitalia** [comment]
One thing to keep in mind is that the lab doesn't like annotations changing underneath them, so I think updating snpeff annotations (as described at the end of #1) because they've changed is not a good scenario. I think it's better to have predictable annotation updates over time that keep everything in sync.

**Comment by bruth** [comment]
We've talked about this before a bit. At what point _is_ it ok to change the annotations? Is the lab aware of the snpEff version being used at the time of their analysis? Once a formal analysis workflow is introduced, tagging an analysis with the current versions of each set of annotations when a sample is first reviewed would prevent cross-versions issues. The caveat to this is that it increases the complexity of the backend since it now requires all queries to be augmented version conditions, e.g. `where variant_effect.version = '1.3.2'`.

**Comment by mitalia** [comment]
I talked about this with the lab last week. They felt that it was important to have a regular schedule that is communicated. We also discussed the need to archive all the annotations for our known list of variants so they could go back and look if that ever became an issue. I'm planning to write the requirements up in a ticket.

**Comment by bruth** [comment]
I figured that. Adding the version field would allow differentiating the annotations on load (which implies they are stored long-term). This would also improve the loader performance by only needing to do inserts rather than upserts.

**Comment by naegelyd** [comment]
Closing in favor of https://github.com/cbmi/varify-data-warehouse/issues/7
