### ISSUE TITLE
Add Main Analysis Screen

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#170]
This screen will show lists of variants grouped by whether or not the variant is related to phenotype or an incidental finding. Within each list, we should display the severity as well (e.g. "realted", "possibly related", VUS, etc..."). Each grouping would have a table of variants that shows what we show in the condensed view as a start.

**Comment by naegelyd** [comment]
This page has been added in the `variant-sets` branch in https://github.com/cbmi/varify/pull/323. Any changes needed can be made under separate issues.
