### ISSUE TITLE
Glacial query performance with gene sets

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#171]
The following SQL is generated for this set of query conditions in production. It basically grinds to a halt and never finishes. It appears that the introduction of more than one gene set is the culprit (a single gene set is very slow, but still finishes). I am concerned that we have a hidden cross-product somewhere that is causing this to spiral out of control (or an outer join where we really mean an inner join). Note that @murphyke has noticed that queries involving multiple genes (ad-hoc, not using gene sets) also perform poorly which may or may not be related. This is an _extremely_ common set of criteria for Varify in production.

![image](https://f.cloud.github.com/assets/21576/2420949/be232e3a-ab7a-11e3-95e8-9fbc304a5c86.png)

The SQL that results is this:

``` SQL
SELECT COUNT(DISTINCT "sample_result"."id") 
FROM "sample_result" 
INNER JOIN "variant" ON ("sample_result"."variant_id" = "variant"."id") 
LEFT OUTER JOIN "variant_effect" ON ("variant"."id" = "variant_effect"."variant_id") 
LEFT OUTER JOIN "transcript" ON ("variant_effect"."transcript_id" = "transcript"."id") 
LEFT OUTER JOIN "gene" ON ("transcript"."gene_id" = "gene"."id") 
LEFT OUTER JOIN "geneset_setobject" ON ("gene"."id" = "geneset_setobject"."object_id") 
LEFT OUTER JOIN "evs" ON ("variant"."id" = "evs"."variant_id") 
LEFT OUTER JOIN "1000g" ON ("variant"."id" = "1000g"."variant_id") 
INNER JOIN "sample" ON ("sample_result"."sample_id" = "sample"."id") 
WHERE ("geneset_setobject"."set_id" IN (10, 1) AND ("evs"."all_af" <= 0.03  OR "evs"."all_af" IS NULL) AND ("1000g"."af" <= 0.03  OR "1000g"."af" IS NULL) AND "sample"."label" IN ('VPseq019-S1-A'))
```

**Comment by naegelyd** [comment]
Marking this as needs info. I am unclear whether this is a Varify, Harvest, or DB issue.

**Comment by naegelyd** [comment]
@mitalia Is this still an issue? I know we were looking into this query a while ago and were considering tweaking some DB settings to improve performance. Did the DB setting changes work(if so, we should note them in the README) or is this still an active problem in Varify?

**Comment by naegelyd** [comment]
Have been unable to recreate. Can reopen later if a solid test case can be produced.
