### ISSUE TITLE
Add die-on-term to uwsgi ini files

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/varify#190]
The syntax in the [uwsgi] ini file should just be:

[uwsgi]
...
die-on-term
...

(You can also use --die-on-term in the uwsgi command.)

Supervisor by default sends processes a TERM signal, which for uWSGI processes causes abrupt termination without cleanup.  With master-worker scenarios, this leaves rogue worker processes behind (that consume max cpu as they get caught in a recursive error reporting situation).

**Comment by naegelyd** [comment]
Closing in favor of adding this on internal instance config. Varify itself can be modified on a per-project/use basis.
