### ISSUE TITLE
Refactor proband selection screen

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#2]
The proband selection screen is messy with the 3 drop down menus. The reality is that the batch is useful for internal tracking, but our users don't know what it means. It will become even less relevant as more people start loading data. I would suggest a control similar to the Harvest ID filter view used for concepts with lots of values. There should be a search bar at the top that allows one to search by project or sample ID. Below that, there should be a paginated table that shows: Sample ID, Project (batch), and Date Loaded. Users should be able to select a single row from this table and apply it to their query
![image](https://f.cloud.github.com/assets/21576/1374770/958bbdbe-3a75-11e3-9c01-bb96199ccd27.png)

**Comment by mitalia** [comment]
I should also comment that this UI should enforce a single sample selection instead of the current behavior that allows multiple samples

**Comment by naegelyd** [comment]
This will require some changes to harvest. Moving this out of the March milestone until I can figure out exactly what those changes are and they are implemented in whichever Harvest component they are needed.

**Comment by naegelyd** [comment]
Fixed in #277.
