### ISSUE TITLE
Add section to README regarding solvebio integration

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#200]
Since there might be instances where people aren't using solvebio but are using varify, the solvebio dependency is now optional. Since it is optional, we need to include instructions on including it in Varify.

**Comment by davecap** [comment]
@naegelyd are the latest README instructions enough to close this?

**Comment by naegelyd** [comment]
Yea, sorry, forgot to close this when I merged. Thanks again for the writeup.
