### ISSUE TITLE
Close cohort popover when a click occurs outside the popover

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#203]
Currently, the user needs to click on the sample popover name that they clicked to show the popover. Clicking anywhere on the page should close the open cohort popover and if that click happens to be on another cohort name, they the existing popover should be closed a the new one shown.

**Comment by mitalia** [comment]
Upgrading this to a bug, in certain cases it can make the UI seem like it's not being properly refreshed.

**Comment by mitalia** [comment]
I'm still seeing this in production, did this change get pushed out to the existing application?

**Comment by naegelyd** [comment]
This has been fixed, there is a different bug that exists with the cohort popover that will be created as a separate issue.
