### ISSUE TITLE
Clinvar queries not precise to the the variant of interest

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#229]
In looking at the clinvar queries in production, I suggest we do some work to partition them a bit. There should be a section for Variant clinvar entries that lists exact matches to the variant in question. There should be a second section that shows all clinvar variants for the gene in question. In the latter case, we should display the actual hgvs string so people can determine what the nature of the variant is.

**Comment by naegelyd** [comment]
This is no longer applicable now that the gene filters were removed as part of the work on #231. The returned results, if any, should now apply directly to the variant and not the genes.
