### ISSUE TITLE
Increase performance of integrated Solvebio/Clinvar code

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#231]
After the Clinvar/Solvebio additions, it now takes upwards of 3 minutes to load a single page of variants on the production instance. This is obviously unacceptable so this integration has been disabled for now. Each call to retrieve a variant results in another call out Solvebio services as can be seen [here](https://github.com/cbmi/varify/blob/master/varify/variants/resources.py#L89-L109). The current method, as linked in the line above, is not acceptable. Two new approaches I can think of are:
1. Batch the variant data into a single request as outlined in #28 and make a single call out to solvebio and then pick the Clinvar variant for each variant out of the response. This has the advantage of limiting the number of calls to Solvebio to 1 per page. However, the data size of the returned data from Solvebio will be much larger and we will have the overhead of parsing and assigning the right Clinvar data to each of the page's results.
2. Update the loader process to run a post-load clinvar command. This command would do all the clinvar lookups for each variant as part of the loading process and should store this in a separate table. Then, we can update the variant resource to lookup the clinvar data directly from the DB. This should add minimal overhead to the resource compared to the case where solvebio is not installed. The only issue here is we might overload the Solvebio API depending on how many variants we have to load Clinvar data for. We will need to check with them. 

@mitalia @bruth @davecap Any other solutions come to mind? Thoughts on the two outlined above? I am in favor of approach `2` above but also very open to suggestions and other approaches.

**Comment by davecap** [comment]
I noticed there were quite a lot of queries going through our API earlier. I definitely think that batching the queries will speed it up quite a lot, but we haven't yet implemented a bulk query resource so it might take a little while to get there.

That said, I should mention that we haven't done much yet in the way of optimizing query speed. There are a number of things we can do right away which should speed it up substantially, so we'll make that our top priority for the next week or so. I think we can get it down to a point that works for you guys, and then combining it with `1` should make it even more efficient.

**Comment by bruth** [comment]
An alternative would be for external resources such as this be defined at separate endpoints. The client can make a request and fill in the areas designated for the ClinVar data. This allows it to independently succeed/fail without burdening the primary payload.

**Comment by bruth** [comment]
If/when a batch endpoint on SolveBio's end is implemented, our resource could be updated use that and split/cache the data per variant.

**Comment by davecap** [comment]
That's a good idea too. We will soon have JS bindings which should allow you to remove slow queries from your internal variant resource and put that on the client side.

The current problem seems to be that each per-variant query may be retrieving hundreds of results from our ClinVar dataset, which means 1+ mb of data may be transferred from our API. It would be much more efficient to query ClinVar for a small subset of results and then allow the end-user to request more when they want them.

**Comment by davecap** [comment]
Seems like my chrome/hipchat connection got all messed up today and I didn't realize I had logged out of the Varify room.

@bruth @naegelyd I'm around this evening or tomorrow any time if you want to discuss fixes.

**Comment by naegelyd** [comment]
This was resolved by removing the gene filter and limiting to 10 results.
