### ISSUE TITLE
Assessments test fail with exception

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#233]
Running the assessment tests alone work fine but when running within the test suite as a whole they fail with an exception. The assessment tests have been disabled in master for now as a result of this error.

**Comment by hassanNS** [comment]
the error message while running multiple tests-->
sqlflush failed
relation "avocado_log" does not exist

**Comment by naegelyd** [comment]
They are [running now](https://github.com/cbmi/varify/blob/master/test_suite.py#L12) and are passing. Marking this as closed unless more information on this pops up.

**Comment by hassanNS** [comment]
what was the fix? Was it the django version issue and it should run fine on my machine? thanks

**Comment by naegelyd** [comment]
Not sure, but they are building on travis and on my machine so I closed the
issue. Haven't identified the fix but didn't look very hard...

On Thu, Apr 24, 2014 at 9:42 AM, Sheik Hassan notifications@github.comwrote:

> what was the fix? Was it the django version issue and it should run fine
> on my machine? thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cbmi/varify/issues/233#issuecomment-41280968
> .

## 

Best Regards,

Donald Naegely
