### ISSUE TITLE
Change non-loader tests to use fixture

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#234]
Other than the `sample_load_process` tests, none of them should use the loader(queue, start workers, etc). Instead they should load a limited data set from a fixture. This will be much faster and incur less overhead than using the "loader" process.

**Comment by naegelyd** [comment]
For example, [DeleteTestCase](https://github.com/cbmi/varify/blob/master/tests/cases/commands/tests.py#L528) and [AssessmentResourceTestCase](https://github.com/cbmi/varify/blob/master/tests/cases/assessments/tests.py#L20) use the "loader" but only really need a sample or two with a few results. This should be loaded from a fixture and not waste a bunch of time loading from collection of VCF's.

**Comment by hassanNS** [comment]
ok this is fixed

**Comment by naegelyd** [comment]
This no longer applies here and, if it is relevant at all, would apply to the `varify-data-warehouse` app. Closing this since it is no longer in the scope of this project or the tests have already been updated to use a fixture as in the [AssessmentResourceTestCase](https://github.com/cbmi/varify/blob/638302de4cae7d54cda8f23df4e3427111bfcf07/tests/cases/assessments/tests.py#L10-L14).
