### ISSUE TITLE
Excel and CSV formatters should use same column order and column set

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#237]
See `Gene` column in Excel versus `gene symbol` and `hgnc_id` in the CSV export as an example.

**Comment by ryanjohara** [comment]
This issue may no longer exist. I was able to reproduce it on one of my older branches, but exports appear to behave consistently on the master branch now.

**Comment by naegelyd** [comment]
@ryanjohara You are correct, closing this now.
