### ISSUE TITLE
Reduce result template to include only the data used by the client

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#239]
I believe that there are a number of fields that are unused by the client. These fields should not be included in the returned data in order to cut down on the size of the data. Marking as `needinfo` originally because I have not identified the unused fields yet.

**Comment by ryanjohara** [comment]
The following fields are included in the response but are not referenced in [result.js](https://github.com/cbmi/varify/blob/master/varify/static/js/src/ui/modals/result.js):

baseq_rank_sum
genotype_quality
haplotype_score
quality_by_depth
sample.batch
sample.count
variant.effects.codon_change
variant.effects.description
variant.effects.functional_class
variant.effects.region
variant.effects.transcript.gene.chr
variant.effects.transcript.gene.families
variant.effects.transcript.gene.id
variant.effects.transcript.gene.name
