### ISSUE TITLE
Create importer for external lists of variants

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#251]
Users may use other tools to reduce the set of variants to ones they wish to investigate and analyze further. Ultimately, they should be able to create a set of variants using forthcoming variant set capabilities. This ticket however is primarily concerned with identifying variants in our database based on a list uploaded by the user. The requirements are as follows:

1) The analyst uploads a spreadsheet with variants in it. This spreadsheet may have one of the following formats for columns:

Form 1: chromosome, start, stop, ref, alt, gt, dbSNP
Form 2: chromosome, start, stop, reference, allele 1, allele 2, dbSNP

2) The uploader processes the spreadsheet, first attempting to identify the variants by dbSNP id (e.g. rs61816760). Failing that, it attempts to find the variant with the matching on the other columns. In cases where Form 1 is used, the genotype is an integer value used in VCF files (see below for more details on that and alt).

3) Variant records that can't be found should be displayed so end-users can inspect them for errors in processing

We have a demo spreadsheet that should allow us to test the feasibility of this approach. We should have a 0% failure rate in the example because the data comes directly from us. To test our detection, we should try to identify 100% of the variants without resorting to the rs number (dbSNP ID). This should allow us to catch any systematic problems that might prevent this from working at scale. 

Here is additional background information adapted from details provided to me by Mehdi Sarmady for handling the "genotype" column as well as the "alt":

In a standard VCF, genotypes (represented as column "GT") are written in number coding where 0 is the reference, 1 is the first alternate allele, 2 is the second alternate allele and so on (More details:http://gatkforums.broadinstitute.org/discussion/1268/how-should-i-interpret-vcf-files-produced-by-the-gatk). 

For example:
Ref: C Alt: T  GT: 0/1 —> Genotype: C/T
Ref: G Alt: GCC   GT: 1/1 —> Genotype: GCC/GCC

In some cases, at a locus, we may not see any reference allele and if it is a heterozygous variant, we see 2 alternate (I.e. Non-reference) alleles. 

Example:
Ref: A, Alt: T, GT: 1/2 —> T/GT

In a multi sample VCF, we may even see third allele. 
Example.  Ref: T  Alt: G,C,A  GT for one sample could be: 1/3 which translates to: G/A.

Regardless, Varify stores these genotypes as a foreign key off the variant table to a table called genotype. There, you will find both the numerical representation used in the VCF (and Form 1) above as well as several other representations.

As for Form 2, it follows the same model but in a non-coded way. Allele1 and Allele2 is the actual genotype of the sample at a given locus. To translate these properly to what we have, the following approach can be used:

If Allele1 is equal to "ref", then Alt = Allele2
If Allele1 is not equal to "ref", then Alt = Allele1,Allele2 (In standard VCF format, multiple alternates are separated by comma which I believe is preserved in Varify "as-is")
Genoype:  Allele1/Allele2 coded numerically as explained above (this corresponds to the "value" column in the genotype table).

**Comment by hassanNS** [comment]
is the demo spreadsheet available on share space?

**Comment by mitalia** [comment]
@muslimgiga I will send to you via email.

**Comment by hassanNS** [comment]
An idea: The user enters the sample name and the batch name along with the uploaded file so that we do not have to deal with issue related to more than one result showing up per variant. Don can elaborate further.

**Comment by mitalia** [comment]
I should have been more clear about this, but the assumption is that the application will be able to tell this loader the specific ID of the sample of interest. So there will be no need for the user to supply a sample + batch to obtain the unique sample ID.

**Comment by naegelyd** [comment]
Yea, those sample and batch fields are just temporary and will be removed
once we figure out exactly how this will interface with the app itself. For
now they are useful while testing.

On Fri, Apr 18, 2014 at 2:59 PM, Michael Italia notifications@github.comwrote:

> I should have been more clear about this, but the assumption is that the
> application will be able to tell this loader the specific ID of the sample
> of interest. So there will be no need for the user to supply a sample +
> batch to obtain the unique sample ID.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cbmi/varify/issues/251#issuecomment-40834814
> .

## 

Best Regards,

Donald Naegely

**Comment by hassanNS** [comment]
cool! That's even better.

**Comment by hassanNS** [comment]
@mitalia "If Allele1 is not equal to "ref", then Alt = Allele1,Allele2 (In standard VCF format, multiple alternates are separated by comma which I believe is preserved in Varify "as-is")"
I believe this is the problem we just discussed. 
ref = G and allele1 = C, allele2 = C. 
By the logic above, alt = C,C. 
Should the query be made as alt = 'C' or alt = 'C,C'

**Comment by mitalia** [comment]
Varify does load the comma-delimited variants "as-is". However, I think there is an error in the description above. I believe that if both allele1 and allele2 are the same, _and_ they are not the ref, then the comma is not used. That scenario is a "Hom Alt" genotype with the alt being C.

**Comment by naegelyd** [comment]
Marking this as done. It has been merged into the variant-sets branch and is being reworked a bit now to create a variant set post-import
