### ISSUE TITLE
Allow creation of variant sets from results

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#252]
Users should be able to create a variant set from their results. If possible, this capability should be supported by adding a creation button directly to the query screen as another option besides "view results". I believe all the existing capabilities of object sets provide the basic persistence we need here. Ideally, when a set is created, it would preserve metadata about the query that created it. Being able to give the set a name and ideally some tags would also be helpful to organizing workflows. To simplify permissions, it would be good to have these owned by a single user. Given the usage envisioned for the application, there is a need to allow sharing of sets between users, but this may be solved by deriving new sets from a starting set or some other mechanism other than shared editing.

**Comment by naegelyd** [comment]
#308 added the ability to create variant sets from a file(Cartagenia export) and from the user's current filter set.
