### ISSUE TITLE
Error when updating filter by deleting selected samples on 'View Results' sidebar

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#263]
This is the initial page
![initial](https://cloud.githubusercontent.com/assets/2774472/2755200/a8b9aaa8-c964-11e3-928b-915b96a32abd.png)

After deleting the sample from the filter, this is the result
![after](https://cloud.githubusercontent.com/assets/2774472/2755201/ba1e46b4-c964-11e3-8a2e-1f5e5c17fa12.png)

This is using both batches from tests/samples/

**Comment by naegelyd** [comment]
Closing in favor of: https://github.com/cbmi/cilantro/issues/523
