### ISSUE TITLE
0/1 1/1 genotypes are a VCF abstract, we should store nucleotides

### ISSUE THREAD

**Issue by leipzig** [chop-dbhi/varify#274]
The storage of the variant.genotype as foreign keys to the genotype table may affect our ability to reliably store loci with many alternate alleles, as well as output new VCFs where we need to consolidate what different alternates were from different samples.

right now our genotype table has entries for 0/0 0/1 1/1 1/2 0/2 and 2/2 but the possibilities are greater

It would probably be better to simply store the two alleles that an individual has.

the genotype (0/0 0/1 1/1 1/2 etc..) output can be written on the fly

as an additional sanity change I would propose separate variant entries for each alternate allele (i.e. no more comma delimited alt fields)

**Comment by mitalia** [comment]
Agree with this. I was poking in here yesterday and felt this was a little bit too faithful a representation of the VCF format and could lead to issues down the line. Can you propose  what you think the variant, sample_result, and genotype tables would look like after this so we can do this? If you don't have bandwidth for this we can likely have Sheik do it. In my mind there are several tasks:

-Modify tables
-Migrate existing data
-Update loaders
-Update loader tests

Also how does snpeff handle the situation where there are multiple alleles at the same location? Do they give a comma-separated list of rs-ID's for example?

**Comment by leipzig** [comment]
I think @awenocur and I can do this.

rsIDs are not allele specific, only position specific
http://www.ncbi.nlm.nih.gov/books/NBK44391/#Submit.we_observed_two_different_snps_at

i have to see what SnpEff is doing for the predicted effects

**Comment by leipzig** [comment]
the snpeff we were using (3.2) only calculates effects for the first allele. looking at 3.6

**Comment by leipzig** [comment]
the proposed schema change discussion has been moved to:
https://github.com/cbmi/varify-data-warehouse/issues/2
