### ISSUE TITLE
Issue reading Variant Excel file

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#276]
Both `xlrd` and `openpyxl` (two standard python libraries for processing xlsx files) fail to read the Variant List excel file after it has been downloaded from the email attachment. 
`xlrd` cannot load the workbook and raises an assertion error while `openpyxl` successfully loads the workbook but the cell values therein are corrupted. 

Upon opening the file and then saving it however (not changing anything in it), the libraries read the xlsx file and raises no errors. 
This is most likely an issue with the excel file itself as xlrd nor openpyxl raises errors while reading other similarly large xlsx files.

**Comment by naegelyd** [comment]
I don't think this is a problem with Varify. If anything, Outlook(or whatever email program) is mucking with the Excel file when downloading the attachement. If this can be shown to be an error in varify, feel free to reopen but I don't think this is relevant.
