### ISSUE TITLE
Delete Query button does not delete query

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#286]
Due to the recent upgrade, the function `deleteQuery` on this line: https://github.com/cbmi/cilantro/blob/master/src/js/cilantro/ui/query/list.js#L66-L66

@naegelyd 
The issue refers to this page.
![screen shot 2014-05-02 at 9 54 18 am](https://cloud.githubusercontent.com/assets/2774472/2863284/537a8a3e-d202-11e3-8278-4de388dca052.png)

**Comment by hassanNS** [comment]
The issue was identified to be in these lines. deleteQuery is not registered. 
https://github.com/cbmi/varify/blob/master/varify/static/js/src/main.js#L165-L187

**Comment by hassanNS** [comment]
This is no longer an issue

**Comment by naegelyd** [comment]
Fixed in #287.
