### ISSUE TITLE
Refractor Variant details modal

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#307]
Idea:
Currently <a href='https://github.com/cbmi/varify/blob/master/varify/static/js/src/ui/modals/result.js'>the result.js modal</a> constructs html in the javascript code. To keep consistency with the other modal windows, it'd be nice to refractor the code to take advantage of Marionette collections and Layouts. 
This way we can have a template for the Variant Details window and reuse this template anytime we want to show information about a variant (such as issue #36)

**Comment by naegelyd** [comment]
This has already been done on the variant-sets branch
