### ISSUE TITLE
Loader does not support single number AD fields

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#310]
We assume that the AD info field will be a variable length number of values as can be seen [here](https://github.com/cbmi/varify/blob/c4273706b0350460c90d6666b54f4847b4839caf/varify/samples/pipeline/utils.py#L82-L88) where we check the length and truthiness of AD. Unfortunately, if someone tried to load a VCF with this format:

```
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
```

the loader will crash because `ad` will be an integer and `len(ad)` will throw an error. We need to handle the case where `ad` is just a single number and cannot always assume that people are loading VCFs with this format for AD:

```
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
```

**Comment by leipzig** [comment]
That is strictly a Varscan convention. I think the loader needs to know it is dealing with Varscan anyway.

**Comment by naegelyd** [comment]
Closed in favor of https://github.com/cbmi/varify-data-warehouse/issues/6
