### ISSUE TITLE
add workaround to readme: LLVM 5.1 interferes with installation of requirements

### ISSUE THREAD

**Issue by awenocur** [chop-dbhi/varify#322]
After installing the XCode 5.1 update, I found that pip would fail to install certain requirements.

This is because LLVM 5.1 now treats certain prior warnings as errors.

The workaround is to add -Qunused-arguments to the CFLAGS environment variable prior to running pip.  I think it would be useful to mention this in the installation instructions.

**Comment by naegelyd** [comment]
Please update the README with the workaround you described above and submit a PR. I have not encountered this issue but it seems to be worth including.

**Comment by naegelyd** [comment]
Fixed in #341.
