### ISSUE TITLE
Add disease associations to variant details

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#33]
I believe we have both the disease associated with a variant as well as the list of diseases associated with the gene from HGMD. I would very much like to display these in the variant details view to start, and potentially in the condensed view as well.

**Comment by mitalia** [comment]
Currently, we display the HGMD disease (which I believe is at the variant level) in the details view under phenotypes. You can view this behavior by filtering by "in HGMD" and picking a variant. You'll see something like this:
![image](https://f.cloud.github.com/assets/21576/2400651/ee46598a-aa0c-11e3-96cc-1f1b8a5d43a8.png)

We should break this section up so that it has:

Phenotypes (variant)
Diabetes, type 2, association with (HGMD: CM076089)

Phenotypes (gene)
CDK11: 
Autosomal dominant inheritance (HPO: 6)
Neoplasia (HPO: 2664)

CDK12:
Diabetes, type 2, association with (HGMD: CM076089)

Note that phenotypes from HPO are mixed with HGMD phenotypes. At some point, we are going to need to disentangle this because having them in the same data model really doesn't make sense. Also note that a variant can affect more than one gene (as in this example) so we need to break out each gene individually.

Where the ID's are, it would be good to either link out to HGMD or HPO. Url format for HPO is as follows but I don't have one for HPO because it's paywalled: http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0002664

(annoyingly our database has truncated leading zeros from these keys so we may not actually be able to construct these.)

One thing that is not clear to me is whether we roll up HGMD annotations at the variant level to the gene level. @bruth would be able to shed a little more light on that perhaps.

**Comment by bruth** [comment]
Models exist associating phenotypes to both variant and gene, but HGMD is only at variant level (not that you couldn't aggregate them to the gene level..). Here relevant part of the loader: https://github.com/cbmi/varify/blob/master/varify/phenotypes/management/subcommands/load.py#L65-L87

``` python
Phenotype.objects.filter(variantphenotype__variant__effects__transcript__gene__symbol='PTEN').distinct()
```
