### ISSUE TITLE
RQ Workers fail to load samples due to get_cache failure

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#333]
The issue I believe is with this line
https://github.com/cbmi/varify/blob/master/varify/variants/pipeline/utils.py#L5
I am not sure if this a problem in of itself but I do know that it cause this nasty error
when the workers are trying to load the samples
![screen shot 2014-06-18 at 1 35 52 pm](https://cloud.githubusercontent.com/assets/2774472/3318073/8579706e-f713-11e3-9873-d109037f9167.png)

PIPELINE_CACHE_ALIAS is being imported as `varify.pipeline` which also happens to be the name of a module. So I think it's getting confused.

**Comment by naegelyd** [comment]
When does this error occur? Can you please add steps to recreate to this issue report?

**Comment by hassanNS** [comment]
@naegelyd after loading in the samples, start the rq workers. 
As the workers try to work on the samples, this error appears in the log and the sample is taken to the failed queues.

The Fix: 
I changed this line: https://github.com/cbmi/varify/blob/master/varify/pipeline/__init__.py#L6
to use 'default' instead of 'varify.pipeline' as the fall back queue.

**Comment by naegelyd** [comment]
Which samples? Are the samples already loaded? Is this using the `master` branch or some other branch?

**Comment by hassanNS** [comment]
@naegelyd this was on the continuous_deployment (now integration_test) branch. The samples weren't loaded. This happened with the samples provided in the docs

**Comment by naegelyd** [comment]
@hassanNS You mentioned a fix in your comment above. Can you please submit a PR with your fix in it? Thanks.

**Comment by naegelyd** [comment]
@hassanNS I've been unable to recreate this error since it was reported. Closing this. If this is still an issue please open a new issue on the `varify-data-warehouse` repo.
