### ISSUE TITLE
Duplicate display of genotypes for heterozygous alternate calls on variant-sets

### ISSUE THREAD

**Issue by awenocur** [chop-dbhi/varify#346]
While using the hosted variant-sets instance, I noticed that both alternate genotypes were displayed twice for each het alt call.

**Comment by naegelyd** [comment]
@awenocur Please post a screen shot of just the erroneous display in the UI or steps to recreate this bug so I can take a look at this.

**Comment by awenocur** [comment]
This is now being addressed in https://github.com/cbmi/varify-data-warehouse/pull/2.  This bug is the result of a model property improperly representing the imported alternate allele sequences.  Since the planned change to the importer updates how multiple alternate alleles are represented, it should resolve this.
