### ISSUE TITLE
Resolving Test Case Clashes

### ISSUE THREAD

**Issue by awenocur** [chop-dbhi/varify#351]
I'm starting this issue to document what I found, so I don't forget it.  This probably won't be worth pursuing for awhile.

When running two TransactionTestCases in series, each of which loads VCF data, the database flushes resulted in transactions that could not be committed, hence leaving the database still populated for the successive test.

This was due to a table being truncated before other tables with foreign keys pointing to it.  Possible solutions would be to ensure that the flush command order these tables properly, or to ensure that the transaction for the flush defer all constraints.

**Comment by naegelyd** [comment]
More comments related to this can be found on https://github.com/cbmi/varify/issues/13.

**Comment by naegelyd** [comment]
This is no longer an issue after the models and loader portions of varify were split out into https://github.com/cbmi/varify-data-warehouse.
