### ISSUE TITLE
handler issue while loading samples and using queue command

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#354]
1) delete your local db
2) use the createdb command to recreate the db
3) use `./bin/manage.py samples queue tests/samples/` to load in data

You will get this error 
![nohandler](https://cloud.githubusercontent.com/assets/2774472/3814015/eae1cc20-1cb7-11e4-8ae6-4972e189cc73.png)

**Comment by bruth** [comment]
Setting up logging handlers are optional and defined in the settings for the deployment. You can read more about logging in Django [here](https://docs.djangoproject.com/en/1.5/topics/logging/).

**Comment by hassanNS** [comment]
Yep. I thought this error was obstructing the queue. But everything loaded ok
