### ISSUE TITLE
Update Docs to include varify-data-warehouse and instructions of use.

### ISSUE THREAD

**Issue by hassanNS** [chop-dbhi/varify#359]
I'm not sure if the same procedure is valid for setting up varify now that the loaders and datamodels are split. Updating the docs would be useful.

**Comment by naegelyd** [comment]
@hassanNS What do you think needs to be added to the `README` to make it more clear? Basically, the only portion of the `README` that is missing is the part related to the loader and that was moved to the `vdw` repository. Please add more details to this issue to indicate what you think is missing. The top of the `README` points the user to `vdw` for more info(see below image) so I am not sure what more could be added here. I think this issue can be closed unless you have specific info the `README` is missing.

![screen shot 2014-09-08 at 11 28 09 am](https://cloud.githubusercontent.com/assets/3911912/4187791/c9ad4b54-376c-11e4-914a-db5f48c942f0.png)
