### ISSUE TITLE
Effect shows integer values in the text field

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#80]
When selecting effects, instead of showing the text values in the text area, only integer values are shown.

![image](https://f.cloud.github.com/assets/21576/2137613/d203d734-9328-11e3-88e0-8605f01ade27.png)

**Comment by naegelyd** [comment]
This will be fixed by the move to a value list once work is completed on https://github.com/cbmi/cilantro/issues/403 and a new version of Cilantro is released and embedded in Varify.
