### ISSUE TITLE
Sample selection concept fails to display currently selected samples

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#81]
When one clicks on the concept on the right hand side, no sample ID's are displayed in the text area, making it appear as though nothing has been selected. To recreate, do the following:
1. Select a sample
2. Edit the sample list to select a different sample
3. Click "Update"
4. Click the concept on the right hand side

It should never be possible for the GUI to be in this state:

![image](https://f.cloud.github.com/assets/21576/2153001/4423de10-9421-11e3-9d7c-4c0d54cd3861.png)

**Comment by naegelyd** [comment]
I am unable to recreate using the steps above. Can you reliably recreate this on the latest version?

**Comment by mitalia** [comment]
This is resolved with the new cilantro.
