### ISSUE TITLE
No selection UI for Functional Class

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#85]
There should be the option to select Missense, Nonsense, or Silent functional classes in the UI but it is entirely empty:

![image](https://f.cloud.github.com/assets/21576/2153208/38b09b38-9424-11e3-8c5a-f004dde883d0.png)

**Comment by naegelyd** [comment]
Fixed a while back in https://github.com/cbmi/varify/commit/bf29cc1fec3a611d2f5ce967a4f3cb5cfe918ba1.
