### ISSUE TITLE
No Selection UI for Effect Region

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#86]
The Effect Region field is part of the "Effect" concept. It should list the following effects:

![image](https://f.cloud.github.com/assets/21576/2153255/e24b0426-9424-11e3-9b11-6869748f8054.png)

However it is totally blank:

![image](https://f.cloud.github.com/assets/21576/2153268/26f67e02-9425-11e3-8ea4-624da7085a79.png)

**Comment by naegelyd** [comment]
Fixed as part of #104
