### ISSUE TITLE
Add default export columns

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#92]
Perhaps @bruth can comment on this behavior, but if I recall correctly, the old Varify came with a pre-defined set of export columns in a specific order so that users would not have to customize which columns they wanted every time. I may be mis-remembering that behavior. However, one thing that is definitely true was that the existing Varify app remembered your columns and their order between analyses, so you only had to configure it once.

In a data discovery app, users often customize columns they want, so it's best to have that be a per-query thing. But for something like this, people tend to want a repeatable process. I therefore think that somehow we either need to set a default set of columns and their order, or we need to persist column selections between queries somehow. I realize neither of these is terribly attractive and might be more than we can get done before getting this out the door. I don't consider this a blocker for release, but we at least should evaluate what the old Varify's behavior was here.

For reference, the order I have in my account in production is as follows:

Gene
refseq_id
varaa
impact
codon_change
rsid    read_depth
coverage_ref
coverage_alt
quality
effect
region
project__label
sample__label
genotype
functional_class
chr
pos
ref
alt
af
afr_af
amr_af
asn_af
eur_af
all_af
aa_af
ea_af
term
pmid
PolyPhen2 Score
PolyPhen2 Prediction
Sift Score
Sift Prediction
hgvs_c
segment
hgvs_p

**Comment by bruth** [comment]
It worked previously by having a "default" DataView that would be used transparently if a user did not already have one for their session (which would only be for first time logins to the app). The alternative way now would be to define a public query that only contains a predefined `view_json` structure. However this would not be good until the feature for requiring query filters are put in place.

**Comment by mitalia** [comment]
Would this new approach work across the board? Seems like that would make the user have to know about selecting the public query. What if they're already working with a public query? Seems like it would be a bit brittle. Is there no way to set default columns in the new Cilantro?

**Comment by bruth** [comment]
Sorry, by "it worked previously" means it still works that way. If you switch to a public query or a shared query, your columns will be switched to the ones for that query.

**Comment by naegelyd** [comment]
@mitalia Varify currently requires users to set at least one column before exporting and keeps their columns(view) as well. The only time the user's view is changed is when they open another query as noted by @bruth above. Is this still an issue? If so, what belongs in the default view? Note, the default will only be used when the user has no view or they open a query that has no view.

**Comment by mitalia** [comment]
This is ok as far as defaults go, but it's a little strange in that users might not expect this to change with things like saved or shared queries. It is surprising for an end user to have their export columns swapped out simply by opening a saved or shared query. In harvest this is clearer because the view changes. But in Varify, it's a bit buried in the exporter.

**Comment by naegelyd** [comment]
I think it will be quite a challenge to separate the view from the query. It is hard to say when one would want the view from the query and when they wouldn't. For example, if I have a particular column sorted and I share a query with you, it is very important that the view is maintained. While this may change you export columns, those are easily restored. I vote that we keep everything as it is now unless users start complaining en masse. I don't think any logic or constraints are worth the effort to maintain or discard the view on a case by case basis. @bruth @mitalia I'm closing this. If you have any strong objections, feel free to reopen.
